alias LS='ls -al'
alias ll='ls -l'
alias la='ls -A'
alias cp='cp'
alias mv='mv -i'
# alias mkdir='mkdir -p -v'
alias oa='open -a'
alias df='df -h'
alias du='du -h -c'
alias R='reset'
alias r='clear'
alias reload='source ~/.bashrc'


alias crossbar='/opt/crossbar/bin/crossbar'
alias docker-down='docker stop $(docker ps -aq) && docker rm $(docker ps -aq)'
alias gs='git status'
