alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -A'
alias rm='mv -t ~/.local/share/Trash/files'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p -v'
alias df='df -h'
alias du='du -h -c'
alias r='reset'
alias reload='source ~/.bashrc'
alias home='cd'
alias downloads='cd ~/Downloads'
alias cs214='cd ~/school/spring_2014/214'
alias school='cd ~/school/fall_2015/'
alias install='sudo apt-get install'
